name: Bug Report
description: File a bug report.
title: "BUG: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: acknowledge
    attributes:
      label: Check the Help Site and GitHub Issues/Discussions
      description: Please check the help site (https://portals-app.help) and the existing GitHub issues, feature requests and discussions first!
      options:
        - label: I have checked and found nothing.
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Portals are you running?
      options:
        - ''
        - 3.2.1.0
        - 3.2.0.3
        - 3.2.0.2
        - 3.2.0.1
        - 3.2.0.0
        - 3.1.0.2
        - 3.1.0.1
        - 3.1.0.0
        - Prior to 3.1.0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: operatingsystem
    attributes:
      label: Operating System
      description: What Windows OS are you running?
      options:
        - ''
        - Windows 11
        - Windows 10
        - Other (Not Supported)
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give as much details as possible!
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce this issue
      placeholder: 1. Do this...
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: What would you expect to happen?
      description: Enter what your would expect to happen.
      placeholder: I would expect it to...
    validations:
      required: true
