name: Feature Request
description: Suggest an improvement or new feature
title: "FEATURE REQUEST: "
labels: ["enhancement"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: acknowledge
    attributes:
      label: Check the Help Site and GitHub Issues/Discussions
      description: Please check the help site (https://portals-app.help) and the existing GitHub issues, feature requests and discussions first!
      options:
        - label: I have checked and found nothing.
          required: true
  - type: textarea
    id: feature-request
    attributes:
      label: What is the enhancement/feature you would like to see?
      description: Give as much details as possible!
      placeholder: Tell us what you want to see!
    validations:
      required: true
